<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/css/styles.css">
    <title>Santhosh Guntupalli - Portfolio</title>
</head>
<body>
    <header>
        <h1>Santhosh Guntupalli</h1>
        <p>Web Developer</p>
    </header>

    <section id="projects">
        <h2>Projects</h2>
        <!-- Your project details go here -->
    </section>

    <section id="skills">
        <h2>Skills</h2>
        <!-- Languages: Python, SQL, C++, C

Cloud Technologies: AWS, GCP, Azure

Bigdata Technologies: Apache Kafka, Apache Spark, Apache Flink, Apache Hadoop, Apache Flume, Apache Nifi

Development and Tools: Docker, Kubernetes, Jenkins, Git, GitHub, REST API, Unix

Machine Leaning and AI: Scikit-learn, TensorFlow, Predictive Analysis, NLP -->
    </section>

    <section id="contact">
        <h2>Contact</h2>
        <!-- Email: santhosh.guntupalli09@gmail.com -->
    </section>

    <footer>
        <p>&copy; 2024 Your Name. All rights reserved.</p>
    </footer>
</body>
</html>

    
