title: Santhosh Guntupalli
email: santhosh.guntupalli09@gmail.com
description: Data Engineer | Machine Learning & AI Expert | Cloud & BI Architect
logo: assets/dp2.jpg
theme: jekyll-theme-minimal
show_downloads: true

# Optional navigation tabs
header_pages:
  - index.md
  - projects.md
  - contact.md

# Plugins for SEO or social links
plugins:
  - jekyll-seo-tag
